openapi: 3.0.3
info:
  title: Ditto Server API - Health
  description: |
    Health check and monitoring endpoints for the Ditto Server API.
    
    **Important**: This API only accepts and returns JSON format. All requests with a body must have `Content-Type: application/json` header.
  version: 1.0.0
  contact:
    name: Ditto Server
  license:
    name: MIT
servers:
  - url: http://localhost:3000
    description: Local development server
security:
  - apiSecret: []

paths:
  /ping:
    get:
      summary: Health check endpoint
      description: Returns a 204 No Content status to indicate the server is running and healthy
      operationId: ping
      responses:
        '204':
          description: No Content - Server is healthy and responsive
          content: {}
        '400':
          description: Bad Request - Invalid content type
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad Request"
                  message:
                    type: string
                    example: "Invalid request format"
        '401':
          description: Unauthorized - Missing or invalid API secret
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
                  message:
                    type: string
                    example: "Authentication required"
        '500':
          description: Internal Server Error - Unexpected server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
                  message:
                    type: string
                    example: "An unexpected error occurred. Please try again later."
      tags:
        - Health

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiSecret:
      type: apiKey
      in: header
      name: X-API-Secret
      description: API secret key required for all requests

tags:
  - name: Health
    description: Health check and monitoring endpoints
